sudo: required
services:
  - docker

before_install:
  - docker build -t ptulsyan/docker-react -f Dockerfile.dev . 

scripts:
  - docker run -e CI=true ptulsyan/docker-react npm run test -- --coverage

language: generic